### ISSUE TITLE
error running for Windows users

### ISSUE THREAD

**Issue by lesniall** [chenkie/react-user-authentication#1]
I encountered an error with a simple fix. 
When running `npm start`  I get `'NODE_ENV' is not recognized as an internal or external command
operable program or batch file.`

To fix just replace (in package.json) the dev-server with `"dev-server": "cross-env NODE_ENV=development hjs-dev-server"` and all should run fine.

**Comment by chenkie** [comment]
Thanks! Feel free to send in a PR if you'd like :)
